// Code generated by MockGen. DO NOT EDIT.
// Source: adapter.go

// Package api_v01 is a generated GoMock package.
package api_v01

import (
	dto "metric-server/internal/dto"
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRequestDtoBuilder is a mock of RequestDtoBuilder interface.
type MockRequestDtoBuilder struct {
	ctrl     *gomock.Controller
	recorder *MockRequestDtoBuilderMockRecorder
}

// MockRequestDtoBuilderMockRecorder is the mock recorder for MockRequestDtoBuilder.
type MockRequestDtoBuilderMockRecorder struct {
	mock *MockRequestDtoBuilder
}

// NewMockRequestDtoBuilder creates a new mock instance.
func NewMockRequestDtoBuilder(ctrl *gomock.Controller) *MockRequestDtoBuilder {
	mock := &MockRequestDtoBuilder{ctrl: ctrl}
	mock.recorder = &MockRequestDtoBuilderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestDtoBuilder) EXPECT() *MockRequestDtoBuilderMockRecorder {
	return m.recorder
}

// CreateCollectDto mocks base method.
func (m *MockRequestDtoBuilder) CreateCollectDto(r *http.Request) (dto.CollectDto, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCollectDto", r)
	ret0, _ := ret[0].(dto.CollectDto)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCollectDto indicates an expected call of CreateCollectDto.
func (mr *MockRequestDtoBuilderMockRecorder) CreateCollectDto(r interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCollectDto", reflect.TypeOf((*MockRequestDtoBuilder)(nil).CreateCollectDto), r)
}
